# Uncomment this line to define a global platform for your project
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'MBProgressHUD', '~> 0.9.1'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.0'
pod 'MJRefresh’
pod 'SVProgressHUD'
pod 'ZXingObjC', '~> 3.0'
pod "SocketRocket"
pod 'UIPlaceholderTextView'

